easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Language
        - App\Entity\Eye
        - App\Entity\Hair
        - App\Entity\Contact
        - App\Entity\Candidate
        - App\Entity\Partner